apiVersion: v1
kind: Service
metadata:
  name: appchat-db-service
  namespace: workshop
spec:
  selector:
    app: mongodb
  ports:
  - name: appchat-db-service
    protocol: TCP
    port: 27017
    targetPort: 27017
