apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: workshop
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVUySFBCSlhYWUdRVkJIWUcK
  AWS_SECRET_ACCESS_KEY: ZEs4NzMzelRLWEtRNnc1SHdZcU9QSUpETWFxREFrays4ZzFrMlNOZgo=
  AWS_DEFAULT_REGION: dXMtZWFzdC0xCg==
  AWS_BUCKET_NAME: YXBwY2hhdG42aXVoCg==
  EMAIL_HOST: c210cC5nbWFpbC5jb20K
  EMAIL_HOST_USER: aHV1bmhhMjEwMzJrMkBnbWFpbC5jb20K
  EMAIL_HOST_PASSWORD: b2J5dyB0anpjIHh3Z3cgbXV6cQo=

  
