apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: workshop
spec:
  selector:
    app: server-deployment
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: ClusterIP
