apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
      - name: server-deployment
        image: huuwxnhax/serverapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGO_STR
          value: mongodb://appchat-db-service:27017/appchat?directConnection=true
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: AWS_DEFAULT_REGION
        - name: AWS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: AWS_BUCKET_NAME
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: EMAIL_HOST
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: EMAIL_HOST_USER
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: EMAIL_HOST_PASSWORD

