apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: workshop
spec:
  rules:
  - host: https://63E9C1252454CF8A5B3E7A0FBE724FCF.gr7.us-east-1.eks.amazonaws.com
    http:
      paths:
      - path: /client
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 3000
      - path: /socket
        pathType: Prefix
        backend:
          service:
            name: socket-service
            port:
              number: 8800
      - path: /server
        pathType: Prefix
        backend:
          service:
            name: server-service
            port:
              number: 5000
  tls:
  - hosts:
    - example.com
    secretName: example-tls-secret
