apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: workshop
spec:
  selector:
    app: client-deployment
    role: client-deployment
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: ClusterIP