apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-deployment
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
      - name: client-deployment
        image: huuwxnhax/clientapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_SERVER_URL
          value: http://server-service:5000
        - name: REACT_APP_PUBLIC_FOLDER
          value: http://server-service:5000/images/
        - name: REACT_APP_SOCKET_URL
          value: ws://socket-service:8800


    
