apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-deployment
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
      - name: client-deployment
        image: huuwxnhax/clientapp:v2
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_SERVER_URL
          value: http://k8s-workshop-appingre-5f98c91283-565151690.us-east-1.elb.amazonaws.com/api
        - name: REACT_APP_PUBLIC_FOLDER
          value: http://server-service:5000/api/images/
        - name: REACT_APP_SOCKET_URL
          value: ws://socket-service:8800


    
